INFO:__main__:***** Running training *****
INFO:__main__:  Num examples = 319940
INFO:__main__:  Num Epochs = 3
INFO:__main__:  Instantaneous batch size per device = 8
INFO:__main__:  Total train batch size (w. parallel, distributed & accumulation) = 32
INFO:__main__:  Gradient Accumulation steps = 2
INFO:__main__:  Total optimization steps = 20000
Steps:   0%|                                                                                                                                                                         | 0/20000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 1670, in <module>
    main()
  File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 1556, in main
    for step, batch in enumerate(train_dataloader):
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/accelerate/data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 420, in <listcomp>
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 377, in __getitem__
    image, conditioning_image = cropped_images[0], cropped_images[1]
IndexError: index 1 is out of bounds for dimension 0 with size 1
[rank0]: Traceback (most recent call last):
[rank0]:   File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 1670, in <module>
[rank0]:     main()
[rank0]:   File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 1556, in main
[rank0]:     for step, batch in enumerate(train_dataloader):
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/accelerate/data_loader.py", line 454, in __iter__
[rank0]:     current_batch = next(dataloader_iter)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/_utils.py", line 706, in reraise
[rank0]:     raise exception
[rank0]: IndexError: Caught IndexError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
[rank0]:     data = self.dataset.__getitems__(possibly_batched_index)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
[rank0]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 420, in <listcomp>
[rank0]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank0]:   File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 377, in __getitem__
[rank0]:     image, conditioning_image = cropped_images[0], cropped_images[1]
[rank0]: IndexError: index 1 is out of bounds for dimension 0 with size 1